-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel_id character varying NOT NULL UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  channel_name text NOT NULL,
  language_code character varying CHECK (language_code IS NULL OR language_code::text ~* '^[a-z]{2}$'::text),
  language_name text,
  is_master boolean DEFAULT false,
  master_channel_id character varying,
  description text,
  thumbnail_url text,
  subscriber_count bigint DEFAULT 0,
  video_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_paused boolean DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT channels_pkey PRIMARY KEY (id),
  CONSTRAINT fk_channels_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_channels_master FOREIGN KEY (master_channel_id) REFERENCES public.channels(channel_id)
);
CREATE TABLE public.localized_videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  source_video_id character varying,
  user_id text NOT NULL,
  project_id uuid,
  channel_id character varying,
  language_code character varying NOT NULL CHECK (language_code::text ~* '^[a-z]{2}$'::text),
  title text,
  description text,
  video_url text,
  thumbnail_url text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['not-started'::character varying, 'queued'::character varying, 'processing'::character varying, 'waiting_approval'::character varying, 'draft'::character varying, 'live'::character varying, 'published'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  duration integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  localized_video_id character varying,
  deleted_at timestamp with time zone,
  CONSTRAINT localized_videos_pkey PRIMARY KEY (id),
  CONSTRAINT localized_videos_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT fk_localized_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_localized_source_video FOREIGN KEY (source_video_id) REFERENCES public.videos(video_id)
);
CREATE TABLE public.processing_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid DEFAULT gen_random_uuid() UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  source_video_id character varying NOT NULL,
  source_channel_id character varying,
  target_languages ARRAY NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'queued'::character varying, 'downloading'::character varying, 'transcribing'::character varying, 'translating'::character varying, 'voice_cloning'::character varying, 'dubbing'::character varying, 'lip_sync'::character varying, 'syncing'::character varying, 'assembling'::character varying, 'processing'::character varying, 'waiting_approval'::character varying, 'uploading'::character varying, 'ready'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  workflow_state jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  error_message text,
  completed_at timestamp with time zone,
  started_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT processing_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_jobs_project FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  name text NOT NULL,
  description text,
  settings jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  channel_id text NOT NULL,
  callback_url text NOT NULL,
  topic text NOT NULL,
  lease_seconds integer NOT NULL,
  expires_at timestamp with time zone,
  secret text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'failed'::text])),
  last_verified_at timestamp with time zone,
  renewal_attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  name text,
  avatar_url text,
  access_token text,
  refresh_token text,
  token_expiry timestamp with time zone,
  preferences jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_id character varying NOT NULL UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  channel_id character varying,
  channel_name text,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  storage_url text,
  video_url text,
  duration integer,
  view_count bigint DEFAULT 0,
  like_count bigint DEFAULT 0,
  comment_count bigint DEFAULT 0,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'queued'::character varying, 'processing'::character varying, 'live'::character varying, 'failed'::character varying, 'not-started'::character varying]::text[])),
  language_code character varying CHECK (language_code IS NULL OR language_code::text ~* '^[a-z]{2}$'::text),
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  video_type character varying CHECK (video_type IS NULL OR (video_type::text = ANY (ARRAY['original'::character varying, 'translated'::character varying]::text[]))),
  source_video_id character varying,
  deleted_at timestamp with time zone,
  CONSTRAINT videos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_videos_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_videos_source FOREIGN KEY (source_video_id) REFERENCES public.videos(video_id)
);
